spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/robert_siur?useSSL=false&characterEncoding=utf8
    username: root
    password: coderslab
